### ISSUE TITLE
"Make" error

### ISSUE THREAD

**Issue by dariotrombello** [mfruba/kernel#16]
Device : Raspberry Pi 3B
Kernel: 4.9.41-Re4son-v7+

Error when typing "make": 

root@kali:~/kernel/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417# make
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
make ARCH=armv7l CROSS_COMPILE= -C /lib/modules/4.9.41-Re4son-v7+/build M=/root/kernel/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417  modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.41-Re4son-v7+'
Makefile:628: arch/armv7l/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/armv7l/Makefile'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-4.9.41-Re4son-v7+'
Makefile:1368: recipe for target 'modules' failed
make: *** [modules] Error 2
root@kali:~/kernel/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417#

**Comment by Borduni** [comment]
Ignore that line xD

**Comment by hector2** [comment]
@Borduni how did you solve that error?

**Comment by Borduni** [comment]
I haven't solved it :(. Nobody is helping me

**Comment by hector2** [comment]
I tried with a fresh install of Kali 2017.1 (kernel 4.9) -> https://archive.kali.org/kali-images/kali-2017.1/kali-linux-2017.1-amd64.iso

But I get the same error

**Comment by Maleick** [comment]
Install the linux headers "apt search linux-headers" and then pick the one that goes with your system found using "uname -r"

Example:

typing: uname -r
gives me : 4.13.0-kali1-amd64
so: apt install linux-headers-4.13.0-kali1-all

**Comment by expl0iter99** [comment]
/home/alpha/Downloads/kernel-master/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417/os_dep/linux/ioctl_cfg80211.c:6139:22: note: (near initialization for ‘rtw_cfg80211_ops.add_virtual_intf’)
cc1: some warnings being treated as errors
/usr/src/linux-headers-4.13.0-kali1-common/scripts/Makefile.build:307: recipe for target '/home/alpha/Downloads/kernel-master/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417/os_dep/linux/ioctl_cfg80211.o' failed
make[4]: *** [/home/alpha/Downloads/kernel-master/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417/os_dep/linux/ioctl_cfg80211.o] Error 1
/usr/src/linux-headers-4.13.0-kali1-common/Makefile:1529: recipe for target '_module_/home/alpha/Downloads/kernel-master/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417' failed
make[3]: *** [_module_/home/alpha/Downloads/kernel-master/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417] Error 2
Makefile:145: recipe for target 'sub-make' failed
make[2]: *** [sub-make] Error 2
Makefile:8: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-kali1-amd64'
Makefile:1368: recipe for target 'modules' failed
make: *** [modules] Error 2


what can be done?

**Comment by Maleick** [comment]
From what I have figured out it appears to only work with Linux Kernel 4.9?

As I am using an update to date copy and I get 4.13 problems like you have.

I am going to install this copy from above and then install the headers and I will report back.

> I tried with a fresh install of Kali 2017.1 (kernel 4.9) -> https://archive.kali.org/kali-images/kali-2017.1/kali-linux-2017.1-amd64.iso

But I get the same  error

**Comment by expl0iter99** [comment]
i can install driver from lwfinger in 4.9 after updating headers for 4.9 but it does not let you use monitor mode. i was able to put it in monitor mode using some modification in source. forgot the procedure. but packet injection was not working. so i place an order for another one now. arthetos this time. p.s. monitor mode works only in older kernel. proper drivers are yet to be coded for this wn722n v2 dongle.

**Comment by latanasov** [comment]
Feel free to try and build from my fork https://github.com/latanasov/kernel. Builds successfully on:
> uname -r
> 4.13.5-200.fc26.x86_64

**Comment by RaminMammadzada** [comment]
The solution is finally here , compiled by kimocoder
Just clone it and follow the instructions :https://github.com/aircrack-ng/rtl8188eus

Additionally, this video also may help you out: 

How To Enable Monitor Mode on TP-Link TL-WN722N v2/v3
https://www.youtube.com/watch?v=NhHiXzqkx_s
