### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sk3lk0** [mfruba/kernel#20]
root@kali:~# cd Desktop/
root@kali:~/Desktop# cd kernel-master/
root@kali:~/Desktop/kernel-master# cd drivers/
root@kali:~/Desktop/kernel-master/drivers# cd TL-WN722N_v2.0-Ralink/
root@kali:~/Desktop/kernel-master/drivers/TL-WN722N_v2.0-Ralink# cd rtl8188EUS_linux_v4.3.0.8_13968.20150417
root@kali:~/Desktop/kernel-master/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417# make
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
make ARCH=armv7l CROSS_COMPILE= -C /lib/modules/4.4.50-v7+/build M=/root/Desktop/kernel-master/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417  modules
make[1]: Entering directory '/usr/src/kernel'
Makefile:617: arch/armv7l/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/armv7l/Makefile'.  Stop.
make[1]: Leaving directory '/usr/src/kernel'
Makefile:1368: recipe for target 'modules' failed
make: *** [modules] Error 2
root@kali:~/Desktop/kernel-master/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417# 

pls help me, add me in skype skelk0_1

**Comment by abhijeet2096** [comment]
whats the output of 
`uname -r`

**Comment by DarkSider777** [comment]
Same problem here on Raspberry pi

pi@DarkSider:~/kernel/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417 $ make
"******************************************"
"NO SKRC,we will use default KSRC"                            "******************************************"
make ARCH=armv7l CROSS_COMPILE= -C /lib/modules/4.9.41-v7+/build M=/home/pi/kernel/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417  modules
make[1]: Entering directory '/usr/src/linux-headers-4.9.41-v7+'                                                             Makefile:628: arch/armv7l/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/armv7l/Makefile'.  Stop.                                                          make[1]: Leaving directory '/usr/src/linux-headers-4.9.41-v7+'Makefile:1368: recipe for target 'modules' failed             make: *** [modules] Error 2
pi@DarkSider:~/kernel/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417 $ uname -r
4.9.41-v7+

**Comment by sk3lk0** [comment]
root@kali:~# uname -r
4.4.50-v7+
