### ISSUE TITLE
Monitor mode not working with TP-LINK TL-WN722N (version 2) on 4.13.0-kali

### ISSUE THREAD

**Issue by yungtravla** [mfruba/kernel#23]
```
$ uname -a
Linux Hostname 4.13.0-kali1-amd64 #1 SMP Debian 4.13.4-2kali1 (2017-10-16) x86_64 GNU/Linux
```

```
$ make
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/4.13.0-kali1-amd64/build M=/root/gitclones/kernel-master/drivers/TL-WN722N_v2.0-Ralink/rtl8188EUS_linux_v4.3.0.8_13968.20150417  modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-kali1-amd64'
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
  Building modules, stage 2.
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
  MODPOST 1 modules
make[1]: Leaving directory '/usr/src/linux-headers-4.13.0-kali1-amd64'
```

```
$ make install
"******************************************"
"NO SKRC,we will use default KSRC"
"******************************************"
install -p -m 644 8188eu.ko  /lib/modules/4.13.0-kali1-amd64/kernel/drivers/net/wireless/
/sbin/depmod -a 4.13.0-kali1-amd64
```

I don't get any errors with `modprobe` or `insmod`

<hr>

```
$ iwconfig
lo        no wireless extensions.

eth0      no wireless extensions.

wlan0     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

```
$ ifconfig wlan0 down
$ iwconfig wlan0 mode Monitor
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan0 ; Invalid argument.
```

```
$ iwconfig 
lo        no wireless extensions.

eth0      no wireless extensions.

wlan0     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Auto  Frequency=2.442 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```

<hr>

```
$ ifconfig
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 17041  bytes 2529439 (2.4 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 17041  bytes 2529439 (2.4 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet6 fe80::e36f:fff:fe60:e4a1  prefixlen 64  scopeid 0x20<link>
        unspec F6:12:F1:1C:06:F7-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 38665  bytes 21429 (20.9 KiB)
        RX errors 0  dropped 38598  overruns 0  frame 0
        TX packets 10  bytes 1209 (1.1 KiB)
        TX errors 0  dropped 3 overruns 0  carrier 0  collisions 0
```

<hr>

I also get this error from `airmon-ng`:

```
Only mac80211 devices on kernel 2.6.33 or higher are officially supported by airmon-ng.
```

<hr>

I was able to get it into monitor mode once using airmon-ng, but the interface was still useless:

```
$ iwconfig 
wlan0mon  IEEE 802.11  Mode:Monitor  Tx-Power=12 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
          
lo        no wireless extensions.

eth0      no wireless extensions.
```

<hr>

This tplink device seem to freeze all my net tools. Commands like `ifconfig` and `iwconfig` freeze with no output. This usually happens when I disconnect the tp-link device.

**Comment by AaronBP** [comment]
Exact same problem here

**Comment by meryemwehbe** [comment]
Same problem , would like to know if there is a solution for it

**Comment by testphone661** [comment]
Yes i resolved the problem thank you. Can you tell me how & what all i have
to do to install my alpha awus036ACH . IM HAVING TROUBLE CONNECTING IT

**Comment by safal2000** [comment]
same problem dude

**Comment by Dogcatfee** [comment]
I too cannot use monitor mode, I have a TL-WN722N V2.1 which may be the issue though it reports as having the same r8188eu driver.

| Ubuntu 17.10
| 4.13.0-16-generic

I can not use monitor mode in Ubuntu 17.10, Kali, or Arch.
If this gets fixed(Or V2.1 getting supported) that would be super cool.

**Comment by elertan** [comment]
Same issue on Linux kali 4.14.0-kali1-rt-amd64 #1 SMP PREEMPT RT Debian 4.14.2-1kali1 (2017-12-04) x86_64 GNU/Linux.

With the TL-WN722N V2.0

**Comment by ikramkhizer** [comment]
elertan can you please provide the link for ubuntu 16.04 of kali linux.

**Comment by elertan** [comment]
@ikramkhizer `ubuntu 16.04 of kali linux.`? It's just a normal ubuntu installation, install this kernel driver given on the repository, and the wireless adapter will switch into monitor mode.

**Comment by mohith7548** [comment]
Is it (v2) working fine in moniter mode after required drivers installed?? 
Reply me please

**Comment by mohith7548** [comment]
Can do packet injection in moniter mode in tp nw722n v2 ,,how was your experience?  Please post me. I am thinking to buy it for pentesting

**Comment by abulhol** [comment]
There are so many helpful answers to all problems with this Wifi stick and Kali Linux on the web. But I am also stuck at the Monitor mode command, exactly like described above. If anybody has a solution, that would be great!

**Comment by elertan** [comment]
@abulhol There seem to be many issues using the driver, I'd suggest you return your device and buy a different one. Anyways, goodluck!

**Comment by ajmwagar** [comment]
Same problem here, on Manjaro with 4.14.1

**Comment by danielvos** [comment]
Same problem wih Kali Linux with kernel 4.14.0-kali3-amd64
Also tried the fix from https://github.com/abhijeet2096/TL-WN722N-V2/blob/master/Readme.md and did not work

**Comment by CerealKiller32** [comment]
no me funciona, no anda, cómo se instalan?, bajo drivers y ninguno funciona, mi tp link titila cada tanto

**Comment by blange123** [comment]
TP-Link TL-WN722N version 3 - Morning all , can this be used with the script to be working with monitor mode??
